# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/cmake/3.21.0/bin/cmake

# The command to remove a file.
RM = /bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/cmake/3.21.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /rhome/tsaik/EpiScale_CrossSection_debug3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /rhome/tsaik/EpiScale_CrossSection_debug3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/cmake/3.21.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/cmake/3.21.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /rhome/tsaik/EpiScale_CrossSection_debug3/CMakeFiles /rhome/tsaik/EpiScale_CrossSection_debug3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /rhome/tsaik/EpiScale_CrossSection_debug3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SceUtils

# Build rule for target.
SceUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SceUtils
.PHONY : SceUtils

# fast build rule for target.
SceUtils/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/SceUtils.dir/build.make src/common/CMakeFiles/SceUtils.dir/build
.PHONY : SceUtils/fast

#=============================================================================
# Target rules for targets named SceInit

# Build rule for target.
SceInit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SceInit
.PHONY : SceInit

# fast build rule for target.
SceInit/fast:
	$(MAKE) $(MAKESILENT) -f src/srcCPU/CMakeFiles/SceInit.dir/build.make src/srcCPU/CMakeFiles/SceInit.dir/build
.PHONY : SceInit/fast

#=============================================================================
# Target rules for targets named SceGPU

# Build rule for target.
SceGPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SceGPU
.PHONY : SceGPU

# fast build rule for target.
SceGPU/fast:
	$(MAKE) $(MAKESILENT) -f src/srcGPU/CMakeFiles/SceGPU.dir/build.make src/srcGPU/CMakeFiles/SceGPU.dir/build
.PHONY : SceGPU/fast

#=============================================================================
# Target rules for targets named runDiscSimulation_M

# Build rule for target.
runDiscSimulation_M: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runDiscSimulation_M
.PHONY : runDiscSimulation_M

# fast build rule for target.
runDiscSimulation_M/fast:
	$(MAKE) $(MAKESILENT) -f src/main/CMakeFiles/runDiscSimulation_M.dir/build.make src/main/CMakeFiles/runDiscSimulation_M.dir/build
.PHONY : runDiscSimulation_M/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f tst/googletest/CMakeFiles/gtest.dir/build.make tst/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f tst/googletest/CMakeFiles/gtest_main.dir/build.make tst/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named UnitTest

# Build rule for target.
UnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTest
.PHONY : UnitTest

# fast build rule for target.
UnitTest/fast:
	$(MAKE) $(MAKESILENT) -f tst/unitTest/CMakeFiles/UnitTest.dir/build.make tst/unitTest/CMakeFiles/UnitTest.dir/build
.PHONY : UnitTest/fast

#=============================================================================
# Target rules for targets named PerfTest

# Build rule for target.
PerfTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PerfTest
.PHONY : PerfTest

# fast build rule for target.
PerfTest/fast:
	$(MAKE) $(MAKESILENT) -f tst/perfTest/CMakeFiles/PerfTest.dir/build.make tst/perfTest/CMakeFiles/PerfTest.dir/build
.PHONY : PerfTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... PerfTest"
	@echo "... SceGPU"
	@echo "... SceInit"
	@echo "... SceUtils"
	@echo "... UnitTest"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runDiscSimulation_M"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

